--------------------------------------------------------
--  DDL for Table CITIES
--------------------------------------------------------

  CREATE TABLE "MURILO"."CITIES" 
   (	"STATE" VARCHAR2(26 BYTE), 
	"CITY_ID" VARCHAR2(26 BYTE), 
	"CITY_NAME" VARCHAR2(26 BYTE), 
	"RIDES_PDAY" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISTRICTS
--------------------------------------------------------

  CREATE TABLE "MURILO"."DISTRICTS" 
   (	"DISTRICT_ID" VARCHAR2(26 BYTE), 
	"DISTRICT_NAME" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DRIVERS
--------------------------------------------------------

  CREATE TABLE "MURILO"."DRIVERS" 
   (	"DRV_ID" VARCHAR2(26 BYTE), 
	"DRV_NAME" VARCHAR2(26 BYTE), 
	"SEX" VARCHAR2(26 BYTE), 
	"AGE" NUMBER(38,0), 
	"CREDIT_CARD" VARCHAR2(26 BYTE), 
	"SURVEY_AVG" NUMBER(38,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INCIDENTS
--------------------------------------------------------

  CREATE TABLE "MURILO"."INCIDENTS" 
   (	"DISTRICT_ID" VARCHAR2(26 BYTE), 
	"SEVERITY" VARCHAR2(26 BYTE), 
	"INSURANCE" VARCHAR2(26 BYTE), 
	"DEATHS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PASSENGERS
--------------------------------------------------------

  CREATE TABLE "MURILO"."PASSENGERS" 
   (	"PAX_ID" VARCHAR2(26 BYTE), 
	"PAX_NAME" VARCHAR2(26 BYTE), 
	"SEX" VARCHAR2(26 BYTE), 
	"AGE" NUMBER(38,0), 
	"CREDIT_CARD" VARCHAR2(26 BYTE), 
	"SURVEY_AVG" NUMBER(38,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RIDES
--------------------------------------------------------

  CREATE TABLE "MURILO"."RIDES" 
   (	"RIDE_ID" VARCHAR2(38 BYTE), 
	"DRIVER_ID" VARCHAR2(26 BYTE), 
	"PASSENGER_ID" VARCHAR2(26 BYTE), 
	"DURATION" VARCHAR2(26 BYTE), 
	"COST" VARCHAR2(26 BYTE), 
	"DEPARTURE_CID" VARCHAR2(26 BYTE), 
	"DEPARTURE_DID" VARCHAR2(26 BYTE), 
	"ARRIVAL_CID" VARCHAR2(26 BYTE), 
	"ARRIVAL_DID" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_CID" ON "MURILO"."CITIES" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_DID" ON "MURILO"."DISTRICTS" ("DISTRICT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DRVID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_DRVID" ON "MURILO"."DRIVERS" ("DRV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAXID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_PAXID" ON "MURILO"."PASSENGERS" ("PAX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_RID" ON "MURILO"."RIDES" ("RIDE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "MURILO"."CITIES" ADD CONSTRAINT "PK_CID" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRICTS
--------------------------------------------------------

  ALTER TABLE "MURILO"."DISTRICTS" ADD CONSTRAINT "PK_DID" PRIMARY KEY ("DISTRICT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DRIVERS
--------------------------------------------------------

  ALTER TABLE "MURILO"."DRIVERS" ADD CONSTRAINT "PK_DRVID" PRIMARY KEY ("DRV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSENGERS
--------------------------------------------------------

  ALTER TABLE "MURILO"."PASSENGERS" ADD CONSTRAINT "PK_PAXID" PRIMARY KEY ("PAX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RIDES
--------------------------------------------------------

  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "PK_RID" PRIMARY KEY ("RIDE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INCIDENTS
--------------------------------------------------------

  ALTER TABLE "MURILO"."INCIDENTS" ADD CONSTRAINT "FK_IDID" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RIDES
--------------------------------------------------------

  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DRVID" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "MURILO"."DRIVERS" ("DRV_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_PAXID" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "MURILO"."PASSENGERS" ("PAX_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DCID" FOREIGN KEY ("DEPARTURE_CID")
	  REFERENCES "MURILO"."CITIES" ("CITY_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DDID" FOREIGN KEY ("DEPARTURE_DID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_ACID" FOREIGN KEY ("ARRIVAL_CID")
	  REFERENCES "MURILO"."CITIES" ("CITY_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_ADID" FOREIGN KEY ("ARRIVAL_DID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
