--------------------------------------------------------
--  DDL for Table DRIVERS
--------------------------------------------------------

  CREATE TABLE "MURILO"."DRIVERS" 
   (	"DRV_ID" VARCHAR2(26 BYTE), 
	"DRV_NAME" VARCHAR2(26 BYTE), 
	"SEX" VARCHAR2(26 BYTE), 
	"AGE" NUMBER(38,0), 
	"CREDIT_CARD" VARCHAR2(26 BYTE), 
	"SURVEY_AVG" NUMBER(38,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DRVID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_DRVID" ON "MURILO"."DRIVERS" ("DRV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DRIVERS
--------------------------------------------------------

  ALTER TABLE "MURILO"."DRIVERS" ADD CONSTRAINT "PK_DRVID" PRIMARY KEY ("DRV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
