--------------------------------------------------------
--  DDL for Table INCIDENTS
--------------------------------------------------------

  CREATE TABLE "MURILO"."INCIDENTS" 
   (	"DISTRICT_ID" VARCHAR2(26 BYTE), 
	"SEVERITY" VARCHAR2(26 BYTE), 
	"INSURANCE" VARCHAR2(26 BYTE), 
	"DEATHS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Ref Constraints for Table INCIDENTS
--------------------------------------------------------

  ALTER TABLE "MURILO"."INCIDENTS" ADD CONSTRAINT "FK_IDID" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
