--------------------------------------------------------
--  DDL for Table RIDES
--------------------------------------------------------

  CREATE TABLE "MURILO"."RIDES" 
   (	"RIDE_ID" VARCHAR2(38 BYTE), 
	"DRIVER_ID" VARCHAR2(26 BYTE), 
	"PASSENGER_ID" VARCHAR2(26 BYTE), 
	"DURATION" VARCHAR2(26 BYTE), 
	"COST" VARCHAR2(26 BYTE), 
	"DEPARTURE_CID" VARCHAR2(26 BYTE), 
	"DEPARTURE_DID" VARCHAR2(26 BYTE), 
	"ARRIVAL_CID" VARCHAR2(26 BYTE), 
	"ARRIVAL_DID" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MURILO"."PK_RID" ON "MURILO"."RIDES" ("RIDE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RIDES
--------------------------------------------------------

  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "PK_RID" PRIMARY KEY ("RIDE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RIDES
--------------------------------------------------------

  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DRVID" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "MURILO"."DRIVERS" ("DRV_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_PAXID" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "MURILO"."PASSENGERS" ("PAX_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DCID" FOREIGN KEY ("DEPARTURE_CID")
	  REFERENCES "MURILO"."CITIES" ("CITY_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_DDID" FOREIGN KEY ("DEPARTURE_DID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_ACID" FOREIGN KEY ("ARRIVAL_CID")
	  REFERENCES "MURILO"."CITIES" ("CITY_ID") ENABLE;
  ALTER TABLE "MURILO"."RIDES" ADD CONSTRAINT "FK_ADID" FOREIGN KEY ("ARRIVAL_DID")
	  REFERENCES "MURILO"."DISTRICTS" ("DISTRICT_ID") ENABLE;
